### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by bozoweed** [Jayreen58/altv-trainer#1]
when i lunch you ressource i get error server side
C:\Users\Administrateur\Desktop\Mystery Altv\resources\trainer\server\server.js:1
import callbacks from "./modules/callbacks";
       ^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at internal/modules/esm/translators.js:100:15
    at Object.meta.done (internal/modules/esm/create_dynamic_module.js:48:9)
    at file:///C:/Users/Administrateur/Desktop/Mystery%20Altv/resources/trainer/server/server.js:9:13
    at ModuleJob.run (internal/modules/esm/module_job.js:111:37)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Loader.import (internal/modules/esm/loader.js:131:24)
[18:58:42][Error] Failed to load resource trainer

**Comment by riccardopll** [comment]
The release is missing the `package.json`. Actual working version coming very soon
